import type { ArchiveProject } from "@/types/archive";

export const archiveProjects: ArchiveProject[] = [
  {
    slug: "lifelong",
    title: "Lifelong",
    client: "Lifelong",
    category: "Commercial Film",
    year: 2026,
    thumbnail: "/projects/lifelong/thumbnail.jpg",
    previewVideo: "/projects/lifelong/final-video.mp4",
  },
  {
    slug: "universal-music",
    title: "Universal Music",
    client: "Universal Music",
    category: "Music Film",
    year: 2026,
    thumbnail: "/projects/universal-music/thumbnail.jpg",
    previewVideo: "/projects/universal-music/final-video.mp4",
  },
  {
    slug: "indiamart-raj-shamani",
    title: "IndiaMART",
    client: "Raj Shamani",
    category: "Founder Story",
    year: 2026,
    thumbnail: "/projects/indiamart-raj-shamani/thumbnail.jpg",
    previewVideo: "/projects/indiamart-raj-shamani/final-video.mp4",
  },
  {
    slug: "raymond",
    title: "Raymond",
    client: "Raymond",
    category: "Campaign Film",
    year: 2025,
    thumbnail: "/projects/raymond/thumbnail.jpg",
    previewVideo: "/projects/raymond/final-video.mp4",
  },
  {
    slug: "pantaloons",
    title: "Pantaloons",
    client: "Pantaloons",
    category: "Fashion Film",
    year: 2025,
    thumbnail: "/projects/pantaloons/thumbnail.jpg",
    previewVideo: "/projects/pantaloons/final-video.mp4",
  },
  {
    slug: "leysha",
    title: "Leysha",
    client: "Leysha",
    category: "Brand Film",
    year: 2025,
    thumbnail: "/projects/leysha/thumbnail.jpg",
    previewVideo: "/projects/leysha/final-video.mp4",
  },
  {
    slug: "tcl",
    title: "TCL",
    client: "TCL",
    category: "Commercial Film",
    year: 2024,
    thumbnail: "/projects/tcl/thumbnail.jpg",
    previewVideo: "/projects/tcl/final-video.mp4",
  },
  {
    slug: "sharp",
    title: "Sharp",
    client: "Sharp",
    category: "Product Film",
    year: 2024,
    thumbnail: "/projects/sharp/thumbnail.jpg",
    previewVideo: "/projects/sharp/final-video.mp4",
  },
  {
    slug: "raaga",
    title: "Raaga",
    client: "Raaga",
    category: "Music Campaign",
    year: 2024,
    thumbnail: "/projects/raaga/thumbnail.jpg",
    previewVideo: "/projects/raaga/final-video.mp4",
  },
];
