import type { MusicArtistProject } from "@/types/music-artist-project";

export const musicArtistProjects: MusicArtistProject[] = [
  {
    slug: "dhanda-nyoliwala-birthday-reel",
    artist: "Dhanda Nyoliwala",
    title: "Birthday Reel",
    clientOrLabel: "VYRL Haryanvi",
    producedVia: "Art-E Media",
    projectType: "Artist Birthday Edit",
    roles: ["Creative Planning & Execution"],
    year: 2025,
    duration: "~40 sec",
    aspectRatio: "9 / 16",
    poster: "/projects/music-dhanda-nyoliwala-birthday-reel/thumbnail.jpg",
    previewVideo: "/projects/music-dhanda-nyoliwala-birthday-reel/final-video.mp4",
    externalUrl:
      "https://www.instagram.com/reel/DJ6PZ8xy_pE/?utm_source=ig_web_copy_link&igsi=MzRlODBiNWFlZA==",
    audioEnabled: true,
  },
  {
    slug: "nit-c-beggo-taur",
    artist: "Nit C",
    title: "Beggo Taur",
    clientOrLabel: "VYRL Haryanvi",
    producedVia: "Art-E Media",
    projectType: "Lyrical Edit",
    roles: ["Video Editing", "Hindi Typography & Motion Graphics"],
    year: 2025,
    duration: "17 sec",
    aspectRatio: "9 / 16",
    poster: "/projects/music-nit-c-beggo-taur/thumbnail.jpg",
    previewVideo: "/projects/music-nit-c-beggo-taur/final-video.mp4",
    externalUrl:
      "https://www.instagram.com/reel/DTkGCyTEjE3/?utm_source=ig_web_copy_link&igsi=MzRlODBiNWFlZA==",
    audioEnabled: true,
  },
  {
    slug: "dhanda-nyoliwala-surrey-bc",
    artist: "Dhanda Nyoliwala",
    title: "Surrey BC",
    clientOrLabel: "VYRL Haryanvi",
    producedVia: "Art-E Media",
    projectType: "Beat-Synced Music Edit",
    roles: ["Video Editing", "Cutout Compositing", "Beat-Synced Motion"],
    year: 2025,
    duration: "21 sec",
    aspectRatio: "9 / 16",
    poster: "/projects/music-dhanda-nyoliwala-surrey-bc/thumbnail.jpg",
    previewVideo: "/projects/music-dhanda-nyoliwala-surrey-bc/final-video.mp4",
    externalUrl:
      "https://www.instagram.com/reel/DI0szpnyyNd/?utm_source=ig_web_copy_link&igsi=MzRlODBiNWFlZA==",
    audioEnabled: true,
  },
  {
    slug: "raftaar-dhanda-chora-baba-ka",
    artist: "Raftaar x Dhanda Nyoliwala",
    title: "Chora Baba Ka",
    clientOrLabel: "VYRL Haryanvi",
    producedVia: "Art-E Media",
    projectType: "Shivratri Topical Music Edit",
    roles: ["Video Editing", "Beat-Synced Fast Cuts", "Frame Animation"],
    year: 2025,
    duration: "17 sec",
    aspectRatio: "9 / 16",
    poster: "/projects/music-raftaar-dhanda-chora-baba-ka/thumbnail.jpg",
    previewVideo: "/projects/music-raftaar-dhanda-chora-baba-ka/final-video.mp4",
    audioEnabled: true,
  },
  {
    slug: "dhanda-nyoliwala-russian-bandana",
    artist: "Dhanda Nyoliwala",
    title: "Russian Bandana — 200M Views Milestone",
    clientOrLabel: "VYRL Haryanvi",
    producedVia: "Art-E Media",
    projectType: "200M Views Milestone Edit",
    roles: [
      "Creative Planning & Execution",
      "Video Editing",
      "BTS-to-Concert Storytelling",
      "Motion Typography",
    ],
    year: 2025,
    duration: "33 sec",
    aspectRatio: "9 / 16",
    poster: "/projects/music-dhanda-nyoliwala-russian-bandana/thumbnail.jpg",
    previewVideo: "/projects/music-dhanda-nyoliwala-russian-bandana/final-video.mp4",
    externalUrl:
      "https://www.instagram.com/reel/DIveuyGyvJv/?utm_source=ig_web_copy_link&igsi=MzRlODBiNWFlZA==",
    audioEnabled: true,
  },
  {
    slug: "dhanda-nyoliwala-maruti-concert",
    artist: "Dhanda Nyoliwala",
    title: "Maruti — Concert Edit",
    clientOrLabel: "VYRL Haryanvi",
    producedVia: "Art-E Media",
    projectType: "Concert Edit",
    roles: ["Video Editing", "Music-Driven Pacing", "Vertical Storytelling"],
    year: 2025,
    duration: "29 sec",
    aspectRatio: "9 / 16",
    poster: "/projects/music-dhanda-nyoliwala-maruti-concert/thumbnail.jpg",
    previewVideo: "/projects/music-dhanda-nyoliwala-maruti-concert/final-video.mp4",
    audioEnabled: true,
  },
];
